# Generated by Django 3.1.5 on 2021-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author_credits', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('removed', models.BooleanField(default=False)),
                ('video_link', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(to='upskill.LearningTag')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author_credits', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='upskill.LearningTag')),
            ],
        ),
    ]
