# Generated by Django 3.1.5 on 2021-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountDTO',
            fields=[
                ('count', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobDTO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Process', 'Process')], max_length=50)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('job_role', models.CharField(default='', max_length=50)),
                ('vacancies', models.IntegerField()),
                ('description', models.TextField()),
                ('min_exp', models.IntegerField(default=0)),
                ('max_exp', models.IntegerField(default=0)),
                ('selection_process', models.TextField(default='')),
                ('last_date', models.DateField(null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Expired', 'Expired'), ('Disabled', 'Disabled'), ('Published', 'Published'), ('Hired', 'Hired')], max_length=50)),
                ('previous_status', models.CharField(choices=[('Draft', 'Draft'), ('Expired', 'Expired'), ('Disabled', 'Disabled'), ('Published', 'Published'), ('Hired', 'Hired')], default='Draft', max_length=50)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('internship', 'Internship'), ('student', 'Student'), ('contract', 'Contract')], max_length=50)),
                ('is_apply_here', models.BooleanField(default=True)),
                ('apply_url', models.CharField(max_length=150, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('min_sal', models.PositiveIntegerField(blank=True, null=True)),
                ('max_sal', models.PositiveIntegerField(blank=True, null=True)),
                ('display_salary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LikedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LikedScholarships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Process', 'Process')], max_length=50)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('vacancies', models.IntegerField()),
                ('description', models.TextField()),
                ('selection_process', models.TextField(default='')),
                ('last_date', models.DateField(null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Expired', 'Expired'), ('Disabled', 'Disabled'), ('Published', 'Published'), ('Selected', 'Selected')], max_length=50)),
                ('previous_status', models.CharField(choices=[('Draft', 'Draft'), ('Expired', 'Expired'), ('Disabled', 'Disabled'), ('Published', 'Published'), ('Selected', 'Selected')], default='Draft', max_length=50)),
                ('is_apply_here', models.BooleanField(default=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
