# Generated by Django 3.1.5 on 2021-02-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('company', '0002_auto_20210219_0541'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshippost',
            name='accepted_degrees',
            field=models.ManyToManyField(to='user.Degree'),
        ),
        migrations.AddField(
            model_name='scholarshippost',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='scholarshippost',
            name='tags',
            field=models.ManyToManyField(to='job.Tag'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.candidate'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.scholarshippost'),
        ),
        migrations.AddField(
            model_name='likedscholarships',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate'),
        ),
        migrations.AddField(
            model_name='likedscholarships',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.scholarshippost'),
        ),
        migrations.AddField(
            model_name='likedjobs',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate'),
        ),
        migrations.AddField(
            model_name='likedjobs',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='accepted_degrees',
            field=models.ManyToManyField(to='user.Degree'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='user.City'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.ManyToManyField(to='job.Tag'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.candidate'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost'),
        ),
    ]
