# Generated by Django 3.1.5 on 2021-03-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210219_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshippost',
            name='apply_url',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshippost',
            name='is_apply_here',
            field=models.BooleanField(default=False),
        ),
    ]
