# Generated by Django 3.1.5 on 2021-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210312_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
