# Generated by Django 3.1.5 on 2021-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('website', models.CharField(blank=True, max_length=5000, null=True)),
                ('address', models.TextField()),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(choices=[('1-10', '1-10'), ('11-20', '11-20'), ('21-50', '21-50'), ('50-200', '50-200'), ('200+', '200+')], default='', max_length=10)),
                ('profile', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('short_code', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('removed', models.BooleanField(default=False)),
                ('facebook', models.CharField(max_length=150, null=True)),
                ('twitter', models.CharField(max_length=150, null=True)),
                ('linkedin', models.CharField(max_length=150, null=True)),
                ('instagram', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_date', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
    ]
